apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: smohan-neon1-cluster
  region: us-west-2
  version: "1.32"

vpc:
  cidr: "172.16.0.0/16"

iam:
  withOIDC: true

managedNodeGroups:
  - name: neon-workers
    instanceType: t3.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 50
    volumeType: gp3
    volumeIOPS: 3000
    volumeThroughput: 125
    privateNetworking: true
    labels:
      role: neon-worker
    tags:
      project: smohan-neon1
    iam:
      withAddonPolicies:
        ebs: true
        efs: false

addons:
  - name: vpc-cni
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
  - name: kube-proxy
  - name: aws-ebs-csi-driver
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
